/**
 * Generates src/styles/utilities.css: attribute utilities over the tokens.
 *
 *   <div mt="sm" px="lg" gap="md" flex="col center" fs="sm" tone="muted">
 *
 * Names come from src/styles/tokens.css: every `--space-<name>` there is a
 * value for every spacing attribute, every `--fs-<name>` a value for `fs`,
 * and so on. Add a token there, then `bun run tokens`. The output is
 * committed; nothing reads this file at runtime.
 */

const tokensCss = await Bun.file(new URL('../src/styles/tokens.css', import.meta.url)).text()

/** Names declared as `--<prefix>-<name>:` in the light theme, in file order. */
const names = (prefix: string) => {
  const found = [...tokensCss.matchAll(new RegExp(`--${prefix}-([\\w-]+)\\s*:`, 'g'))].map((m) => m[1]!)
  return [...new Set(found)]
}

/** Spacing attributes: name, the property it sets, and whether `auto` is allowed. */
const SPACING: [attr: string, prop: string, auto: boolean][] = [
  ['m', 'margin', true],
  ['mt', 'margin-top', true],
  ['mr', 'margin-right', true],
  ['mb', 'margin-bottom', true],
  ['ml', 'margin-left', true],
  ['mx', 'margin-inline', true],
  ['my', 'margin-block', true],
  ['p', 'padding', false],
  ['pt', 'padding-top', false],
  ['pr', 'padding-right', false],
  ['pb', 'padding-bottom', false],
  ['pl', 'padding-left', false],
  ['px', 'padding-inline', false],
  ['py', 'padding-block', false],
  ['gap', 'gap', false],
  ['gx', 'column-gap', false],
  ['gy', 'row-gap', false],
]

const fromNames = (prefix: string, prop: string) =>
  Object.fromEntries(names(prefix).map((n) => [n, `${prop}: var(--${prefix}-${n})`]))

/**
 * Attributes whose values are names, each mapped to one declaration block.
 * `''` is the bare attribute: `<div border>` renders as `border=""`.
 */
const KEYWORDS: Record<string, Record<string, string>> = {
  fs: fromNames('fs', 'font-size'),
  fw: Object.fromEntries([400, 500, 600, 700].map((w) => [String(w), `font-weight: ${w}`])),
  tone: Object.fromEntries(['ink', 'muted', 'accent', 'student', 'good', 'warn', 'bad'].map((k) => [k, `color: var(--${k})`])),
  bg: Object.fromEntries(['bg', 'surface', 'sunken', 'hover', 'active', 'accent', 'student', 'good-soft', 'bad-soft'].map((k) => [k, `background: var(--${k})`])),
  radius: fromNames('radius', 'border-radius'),
  shadow: fromNames('shadow', 'box-shadow'),
  border: {
    '': 'border: 1px solid var(--line)',
    t: 'border-top: 1px solid var(--line)',
    r: 'border-right: 1px solid var(--line)',
    b: 'border-bottom: 1px solid var(--line)',
    l: 'border-left: 1px solid var(--line)',
  },
  items: Object.fromEntries(['start', 'center', 'end', 'stretch', 'baseline'].map((k) => [k, `align-items: ${k}`])),
  justify: {
    start: 'justify-content: flex-start',
    center: 'justify-content: center',
    end: 'justify-content: flex-end',
    between: 'justify-content: space-between',
    around: 'justify-content: space-around',
  },
  // `grid` alone is display: grid; `grid="3"` is three equal columns.
  // (Not `cols`: <textarea> already has a `cols` attribute.)
  grid: {
    '': 'display: grid',
    ...Object.fromEntries([1, 2, 3, 4, 5, 6].map((n) => [String(n), `display: grid; grid-template-columns: repeat(${n}, minmax(0, 1fr))`])),
  },
  w: { full: 'width: 100%' },
  h: { full: 'height: 100%', screen: 'height: 100dvh' },
  text: Object.fromEntries(['left', 'center', 'right'].map((k) => [k, `text-align: ${k}`])),
}

/** `flex` takes words in any order: `<div flex="col center">`. Matched with `~=`. */
const FLEX_WORDS: Record<string, string> = {
  col: 'flex-direction: column',
  row: 'flex-direction: row',
  wrap: 'flex-wrap: wrap',
  center: 'align-items: center; justify-content: center',
  inline: 'display: inline-flex',
}

/** Bare attributes with one meaning. */
const FLAGS: Record<string, string> = {
  grow: 'flex: 1 1 0; min-width: 0',
  truncate: 'overflow: hidden; text-overflow: ellipsis; white-space: nowrap',
  'sr-only':
    'position: absolute; width: 1px; height: 1px; margin: -1px; padding: 0; overflow: hidden; clip-path: inset(50%); white-space: nowrap; border: 0',
}

const space = names('space')
const css: string[] = ['/* Generated by scripts/utilities.ts from tokens.css. Edit those, then `bun run tokens`. */', '', '@layer utilities {']
const rule = (sel: string, body: string) => css.push(`  ${sel} { ${body}; }`)

for (const [attr, prop, auto] of SPACING) {
  for (const n of space) rule(`[${attr}="${n}"]`, `${prop}: var(--space-${n})`)
  if (auto) rule(`[${attr}="auto"]`, `${prop}: auto`)
  css.push('')
}

rule('[flex]', 'display: flex')
for (const [word, body] of Object.entries(FLEX_WORDS)) rule(`[flex~="${word}"]`, body)
css.push('')

for (const [attr, values] of Object.entries(KEYWORDS)) {
  for (const [v, body] of Object.entries(values)) rule(`[${attr}="${v}"]`, body)
  css.push('')
}

for (const [attr, body] of Object.entries(FLAGS)) rule(`[${attr}]`, body)
css.push('')
css.push('  [print="only"] { display: none !important; }')
css.push('  @media print {')
css.push('    [print="hide"] { display: none !important; }')
css.push('    [print="only"] { display: revert !important; }')
css.push('  }')
css.push('}', '')

await Bun.write(new URL('../src/styles/utilities.css', import.meta.url), css.join('\n'))
console.log(`utilities.css: ${css.filter((l) => l.includes('{ ')).length} rules; space: ${space.join(' ')}`)
